{% set version = "0.10" %}

package:
  name: viscm
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/v/viscm/viscm-{{ version }}.tar.gz
  sha256: 0a30dd19bc2b6cdbcf198b2526b1bd11e8031fa0df6e2b3cd7d95ad792550643

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.9
    - pip
    - numpy  # it is noarch and the numpy import at setup.py is a bug
  run:
    - python >=3.9
    - numpy
    - matplotlib-base
    - colorspacious
    - scipy
    - PySide2

about:
  home: https://github.com/bids/viscm
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A colormap tool

extra:
  recipe-maintainers:
    - mfisher87
    - kthyng
