{% set version = "0.10" %}
{% set build_number = "0" %}
{% set sha256 = "0a30dd19bc2b6cdbcf198b2526b1bd11e8031fa0df6e2b3cd7d95ad792550643" %}


package:
  name: viscm
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/v/viscm/viscm-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: {{ build_number }}
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.9
    - pip
  run:
    - python >=3.9
    - numpy ~=1.22
    - colorspacious ~=1.1
    - scipy ~=1.8
    - matplotlib ~=3.5
    # For some reason, the below config fails to build (see
    # https://github.com/conda-forge/viscm-feedstock/pull/11#issuecomment-1589953730)
    # - matplotlib-base ~=3.5
    # - PySide6

about:
  home: https://github.com/bids/viscm
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A colormap tool

extra:
  recipe-maintainers:
    - mfisher87
    - kthyng
